version: '2'

services:
  app_php:
    build: docker/php
    restart: "always"
    networks:
      - "default"
    volumes:
      - "$PWD:/data/app"
    working_dir: "/data/app"
    command: "php -S 0.0.0.0:80 -t src/Lw/Infrastructure/Ui/Web/Silex/Public"
  app_domain_events:
    build: docker/php
    restart: "always"
    networks:
      - "default"
    volumes:
      - "$PWD:/data/app"
    working_dir: "/data/app"
    command: "php bin/console domain:events:spread"
  rabbitmq:
    image: rabbitmq:management
    container_name: lw_rabbit
    networks:
      - "default"
  elastic:
    image: elasticsearch
    container_name: lw_elastic
    networks:
      - "default"
  kibana:
    image: kibana
    container_name: lw_kibana
    depends_on:
      - elastic
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    networks:
      - "default"
  redis:
    image: redis
    container_name: lw_redis
    networks:
      - "default"

networks:
  default:
    driver: bridge